### ISSUE TITLE
Yaml class missing when using --audit-db

### ISSUE THREAD

**Issue by jeroenvermeulen** [fancyguy/composer-security-check-plugin#16]
```
jeroen@Laptop:/data/repos/insecure-project$ composer audit --audit-db ../security-advisories

Fatal error: Uncaught Error: Class 'Symfony\Component\Yaml\Parser' not found in /data/repos/insecure-project/vendor/fancyguy/composer-security-check-plugin/src/Checker/OfflineChecker.php:31
Stack trace:
#0 /data/repos/insecure-project/vendor/fancyguy/composer-security-check-plugin/src/Command/AuditCommand.php(45): FancyGuy\Composer\SecurityCheck\Checker\OfflineChecker->__construct('../security-adv...', Object(Symfony\Component\Console\Style\SymfonyStyle))
#1 phar:///Users/jeroen/bin/composer.phar/vendor/symfony/console/Command/Command.php(241): FancyGuy\Composer\SecurityCheck\Command\AuditCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///Users/jeroen/bin/composer.phar/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///Users/jeroen/bin/composer.phar/vendor/symfony/console/Application in /data/repos/insecure-project/vendor/fancyguy/composer-security-check-plugin/src/Checker/OfflineChecker.php on line 31
```

```
jeroen@Laptop:/data/repos/insecure-project$ composer info

[CRITICAL] 1 package has known vulnerabilities.
doctrine/annotations                    v1.6.0  Docblock Annotations Parser
doctrine/cache                          v1.8.0  Caching library offering an object-oriented API for many cache backends
doctrine/collections                    v1.5.0  Collections Abstraction library
doctrine/common                         v2.9.0  Common Library for Doctrine projects
doctrine/event-manager                  v1.0.0  Doctrine Event Manager component
doctrine/inflector                      v1.3.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/lexer                          v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/persistence                    v1.0.1  Doctrine Persistence abstractions.
doctrine/reflection                     v1.0.0  Doctrine Reflection component
fancyguy/composer-security-check-plugin 1.1.0   Checks installed dependencies against SensioLabs security advisory database
psr/log                                 1.0.2   Common interface for logging libraries
symfony/icu                             v1.0.1  Contains an excerpt of the ICU data and classes to load it.
symfony/polyfill-ctype                  v1.9.0  Symfony polyfill for ctype functions
symfony/symfony                         v2.5.2  The Symfony PHP framework
twig/twig                               v1.35.4 Twig, the flexible, fast, and secure template language for PHP
```

**Comment by jeroenvermeulen** [comment]
Is this fixed by https://github.com/magehost/composer-security-check-plugin/commit/0c89ef44bb6ab0e0cfcbbd4d5a01390f719d1c3c ? 
Was not able to get it working, maybe only works when installing through Packagist?

**Comment by sbuzonas** [comment]
You are right. I have it globally installed and another plugin pulls in the dep.
